package br.ufg.inf.menu;

public interface MensagensSistemaDeVendas {
	public static final String ADICIONAR_PRODUTO = "Adicionar produto";
	public static final String ADICIONAR_PRODUTO_ESTOQUE = "Adicionar produto ao estoque";
	public static final String BEM_VINDO = "Bem-vindo ao Sistema de Vendas!";
	public static final String CARTAO = "Cartão";
	public static final String CODIGO = "Código";
	public static final String CODIGO_INVALIDO = "Código inválido, favor informar apenas números";
	public static final String CONSULTAR_PRECO = "Consultar preço";
	public static final String DADOS_LOGIN_INVALIDOS = "Login ou senha inválidos, favor informe seus dados novamente.";
	public static final String DESCRICAO = "Descrição";
	public static final String DINHEIRO = "Dinheiro";
	public static final String EMITIR_RELATORIO_ESTOQUE = "Emitir relatório de estoque";
	public static final String EMITIR_RELATORIO_VENDA = "Emitir relatório de venda";
	public static final String ESCOLHER_CAIXA = "Escolher caixa";
	public static final String INFORME_CODIGO_PRODUTO = "Informe o código do produto desejado";
	public static final String INFORME_VALOR_PAGO = "Informe o valor pago";
	public static final String FAVOR_INFORMAR_DADOS_PRODUTO = "Favor informar os dados do produto:";
	public static final String FORMA_PAGAMENTO = "Favor informar a forma de pagamento";
	public static final String FINALIZAR_VENDA = "Finalizar venda";
	public static final String INICIAR_NOVO_CAIXA = "Iniciar novo caixa";
	public static final String INICIANDO_VENDA = "Iniciando venda...";
	public static final String LOGIN = "Login";
	public static final String LOGOFF = "Logoff";
	public static final String NENHUM_PRODUTO = "Nenhum produto foi adicionado, favor incluir algum produto no pedido.";
	public static final String OBRIGADO_POR_UTILIZAR = "Obrigado por utilizar o Sistema de Vendas!";
	public static final String PEDIDO_VENDA = "Pedido de venda";
	public static final String PRECO = "Preço";
	public static final String PRECO_INVALIDO = "Preço inválido, favor colocar no formato 0.00";
	public static final String PRODUTO_ADICIONADO_ESTOQUE = "Produto adicionado ao estoque com sucesso.";
	public static final String PRODUTO_JA_ADICIONADO = "Produto já adicionado, informe outro produto.";
	public static final String PRODUTO_NAO_ENCONTRADO = "Produto não encontrado, favor informar um código de produto válido.";
	public static final String QUANTIDADE = "Quantidade";
	public static final String QUANTIDADE_INVALIDA = "Quantidade inválida, informe no formato inteiro ou decimal.";
	public static final String REALIZAR_VENDA = "Realizar venda";
	public static final String SAIR = "Sair";
	public static final String SELECIONE_UMA_FUNCAO = "Por favor, selecione a função desejada:";
	public static final String SELECIONE_CAIXA = "Selecione o caixa desejado:";
	public static final String SENHA = "Senha";
	public static final String TROCO = "Troco";
	public static final String USUARIO = "Usuário";
	public static final String VALOR_PRODUTO = "Valor do produto";
	public static final String VALOR_TOTAL_VENDA = "Valor total da venda";
	public static final String VENDA_FINALIZADA = "Venda finalizada com sucesso.";
	public static final String VOLTAR = "Voltar";
}
